backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

site_url: https://craigfoden.netlify.app/

# These lines should *not* be indented
media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "test" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/test" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'data'
    label: 'Data'
    files:
      - file: 'data/intro.yaml'
        label: 'Intro data'
        name: 'Intro'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean'}
          - { label: 'Section title', name: 'section_title', widget: 'string'}
          - { label: 'Text', name: 'text', widget: 'string'}
      - file: 'data/first.yaml'
        label: 'First data'
        name: 'First'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean'}
          - { label: 'Section title', name: 'section_title', widget: 'string'}
          - label: 'features'
            name: 'features'
            widget: 'object'
            collapsed: true
            fields:
              -  name: 'icon'
                 label: 'icon'
                 widget: 'string'
              -  name: 'heading'
                 label: 'Heading'
                 widget: 'string'
              -  name: 'text'
                 label: 'text'
                 widget: 'string'
                   
      - file: 'data/second.yaml'
        label: 'Second data'
        name: 'Section Two'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean'}
          - { label: 'Section title', name: 'section_title', widget: 'string'}
      - file: 'data/third.yaml'
        label: 'Book. Third data'
        name: 'Section Two book'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean'}
          - { label: 'Section title', name: 'section_title', widget: 'string'}
          - { label: 'Section text', name: 'section_text', widget: 'string'}
      - file: 'data/footer.yaml'
        label: 'Footer section'
        name: 'footer'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean'}
          - { label: 'Footer menu', name: 'footer_menu', widget: 'boolean'}
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - { label: 'title', name: 'title', widget: 'string'}
              - { label: 'phone', name: 'phone', widget: 'string'}
              - { label: 'email', name: 'email', widget: 'string'}
              - label: 'address'
                name: 'address'
                widget: 'object'
                fields:
                  - { label: 'street', name: 'street', widget: 'string'}
                  - { label: 'town', name: 'town', widget: 'string'}
                  - { label: 'Postcode', name: 'zip', widget: 'string'}
                  - { label: 'country', name: 'country', widget: 'string'}
              
